# Generated by Django 5.0.3 on 2024-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("payment_method", models.CharField(max_length=100)),
                (
                    "rating_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("account_number", models.CharField(max_length=50)),
                (
                    "rating_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("license_number", models.CharField(max_length=100)),
                ("car_model", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("userId", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=100)),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("account_number", models.CharField(max_length=50)),
                (
                    "rating_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("tax_number", models.CharField(max_length=100)),
            ],
        ),
    ]
