# Generated by Django 5.0.3 on 2024-03-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="buyer",
            table="buyer",
        ),
        migrations.AlterModelTable(
            name="driver",
            table="driver",
        ),
        migrations.AlterModelTable(
            name="seller",
            table="seller",
        ),
    ]
