# Generated by Django 5.0.3 on 2024-03-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_buyer_table_alter_driver_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="buyers/profile_images/"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="drivers/profile_images/"
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="sellers/profile_images/"
            ),
        ),
    ]
