# Generated by Django 5.0.3 on 2024-04-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="recipient",
            new_name="reciever",
        ),
    ]
