# Generated by Django 5.0.3 on 2024-04-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_recipient_message_reciever"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="reciever",
            new_name="receiver",
        ),
    ]
