# Generated by Django 5.0.3 on 2024-05-11 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_customuser_rating_value_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.driverprofile",
            ),
        ),
    ]
